### PR TITLE
Mergin from McAfee SIEM cli and python api

### PR DESCRIPTION
**Pull request by tristanlatr**
mfe_saw base rewrite and Query objects to deal with alarms and events.
Testing works good.
Still Work In progress...
ESM, Datasource, DevTree classes from mfe_saw have been deleted.

### CODE REVIEW

**Comment by tristanlatr** [comment]
Hello,

I forked the project mfe_saw a few weeks ago to add some new query feature and ended un rewrite the base objects.
So I'm proposing this as a base for this new version :)

**Comment by tristanlatr** [comment]
Hi,

Just to inform you that you can ignore this PR as this code lives under the name of msiem at https://github.com/tristanlatr/msiem

Thanks,

**Comment by tristanlatr** [comment]
Hi
I' m working the alarm searching, filtering, and management. Also the
qryExecuteDetails command with filters also on my end. We could merge our
code !

**Comment by andywalden** [comment]
Hi Tristan - Please send me an email at aw @ krakencodes.com and we can find a path. Thanks!

**Pull request closed without merging**
